import { db } from '../src/lib/db';
import { ministryTeams, ministryCategories } from '../src/lib/schema';
import { eq } from 'drizzle-orm';

// Ministry data from the CSV
const ministryData = [
  {
    name: "Bereavement Meals Team",
    contactHeading: "Contact Group Leader:",
    leader: "Janie Lewis",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Serve As Needed",
    regularMeetingTime: "",
    description: "This group provides refreshments and (if requested) light finger-food meals for family and friends when memorial services are held here at FCC.",
    graphicImage: "https://express.adobe.com/id/urn:aaid:sc:VA7:376d6c0c-839d-53d3-a0bc-ecfeb9d41d58?invite=true&accept=true&promoid=Z2G1FQKR&mv=other",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Janie Lewis",
    contactEmail: "janie.lewis@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Serve As Needed",
    location: "",
    skillsNeeded: [],
    timeCommitment: "As needed"
  },
  {
    name: "Compassionate Cooks",
    contactHeading: "Contact Group Leader:",
    leader: "Kathy Cooper",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Serve As Needed",
    regularMeetingTime: "",
    description: "Working in teams, this group provides occasional meals for people struggling with illness, recovering from surgeries, or otherwise in need of short-term help.",
    graphicImage: "",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Kathy Cooper",
    contactEmail: "kathy.cooper@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Serve As Needed",
    location: "",
    skillsNeeded: [],
    timeCommitment: "As needed"
  },
  {
    name: "Forward Training Center",
    contactHeading: "Contact Outreach Chair:",
    leader: "Jerry Tidwell",
    leaderContact: "",
    type: ["Partner Organization"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "Provides resources and job skills training for Hood County adults looking to enter the workforce and/or improve their lives.",
    graphicImage: "",
    recurringType: "Never",
    category: "Partner Organization",
    contactPerson: "Jerry Tidwell",
    contactEmail: "jerry.tidwell@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Varies"
  },
  {
    name: "JYF (Junior Youth Fellowship)",
    contactHeading: "Contact Pastor:",
    leader: "Emily Newby",
    leaderContact: "",
    type: ["Discipleship & Education", "Fellowship & Interest"],
    regularMeetingType: "Meets for Special Events",
    regularMeetingTime: "",
    description: "Students in grades 3-5 share food, fellowship, learning, worship, and fun.",
    graphicImage: "",
    recurringType: "Never",
    category: "Discipleship & Education",
    contactPerson: "Emily Newby",
    contactEmail: "emily.newby@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Special Events",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Event-based"
  },
  {
    name: "Meals on Wheels",
    contactHeading: "Contact Volunteer:",
    leader: "John Pelham",
    leaderContact: "",
    type: ["Partner Organization"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "As part of the broader Hood County Meals on Wheels effort, this group works to bring food (and love!) to homebound persons. You can work as much as little as you like; there are always routes available!",
    graphicImage: "",
    recurringType: "Never",
    category: "Partner Organization",
    contactPerson: "John Pelham",
    contactEmail: "john.pelham@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Flexible"
  },
  {
    name: "Medical Supply Closet",
    contactHeading: "",
    leader: "Nancy Womack",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "This resource of the church exists to share medical supplies such as wheelchairs, walkers, and surgery recovery tools with the church and the community. If you need to borrow or would like to donate, contact the church office.",
    graphicImage: "",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Nancy Womack",
    contactEmail: "nancy.womack@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "",
    location: "Church Office",
    skillsNeeded: [],
    timeCommitment: "As needed"
  },
  {
    name: "Mission Granbury",
    contactHeading: "Contact Outreach Chair:",
    leader: "Jerry Tidwell",
    leaderContact: "",
    type: ["Partner Organization"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "Provides a variety of emergency services and resources to families in need in Hood County, including rent, utility, prescription, and gas assistance, emergency shelter, food, clothing, and more.",
    graphicImage: "",
    recurringType: "Never",
    category: "Partner Organization",
    contactPerson: "Jerry Tidwell",
    contactEmail: "jerry.tidwell@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Varies"
  },
  {
    name: "Paluxy River Children's Advocacy",
    contactHeading: "Contact Outreach Chair:",
    leader: "Jerry Tidwell",
    leaderContact: "",
    type: ["Partner Organization"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "Advocates for children that are victims of abuse and neglect.",
    graphicImage: "",
    recurringType: "Never",
    category: "Partner Organization",
    contactPerson: "Jerry Tidwell",
    contactEmail: "jerry.tidwell@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Varies"
  },
  {
    name: "Prayer Shawl & Quilting Ministry",
    contactHeading: "Contact Group Leader:",
    leader: "Carole Wright",
    leaderContact: "",
    type: ["Service & Ministry", "Fellowship & Interest"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "This long-running and faithful group wraps people in love and prayer through the crafting of beautiful shawls and quilts.",
    graphicImage: "",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Carole Wright",
    contactEmail: "carole.wright@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "",
    location: "",
    skillsNeeded: ["Sewing", "Crafting", "Prayer"],
    timeCommitment: "Flexible"
  },
  {
    name: "Property/Grounds Team",
    contactHeading: "Contact Property Chair:",
    leader: "Bruce Morgan",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "This team cares for our facility, doing everything from mowing to special repairs and projects. Help out with regular maintenance, or take on a special project as you have time!",
    graphicImage: "",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Bruce Morgan",
    contactEmail: "bruce.morgan@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "",
    location: "Church Grounds",
    skillsNeeded: ["Maintenance", "Landscaping", "Repairs"],
    timeCommitment: "Flexible"
  },
  {
    name: "Ruth's Place Clinic & Outreach Center",
    contactHeading: "Contact Outreach Chair:",
    leader: "Jerry Tidwell",
    leaderContact: "",
    type: ["Partner Organization"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "Provides healthcare and social services to uninsured residents of Hood County.",
    graphicImage: "",
    recurringType: "Never",
    category: "Partner Organization",
    contactPerson: "Jerry Tidwell",
    contactEmail: "jerry.tidwell@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Varies"
  },
  {
    name: "Safety Team",
    contactHeading: "Contact Group Leader:",
    leader: "Danny Dwight",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Occasional Meetings; Ongoing Opportunities to Serve",
    regularMeetingTime: "",
    description: "This team keeps an eye on things on Sunday mornings to help keep us all safe.",
    graphicImage: "",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Danny Dwight",
    contactEmail: "danny.dwight@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sunday mornings",
    location: "Church",
    skillsNeeded: ["Safety awareness", "Communication"],
    timeCommitment: "Sunday mornings"
  },
  {
    name: "Salvation Army",
    contactHeading: "Contact Outreach Chair:",
    leader: "Jerry Tidwell",
    leaderContact: "",
    type: ["Partner Organization"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "Assists families in need in times of crisis, with a strong recent focus on the needs of foster youth and families.",
    graphicImage: "",
    recurringType: "Never",
    category: "Partner Organization",
    contactPerson: "Jerry Tidwell",
    contactEmail: "jerry.tidwell@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Varies"
  },
  {
    name: "Scholarship Ministry",
    contactHeading: "Contact Scholarship Chair:",
    leader: "Linda Keithley",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Occasional Meetings. Fundraiser luncheon annually in May.",
    regularMeetingTime: "",
    description: "Our Scholarship Team manages our Scholarship Fund, plans an annual fundraiser luncheon, and distributes scholarships to students connected to our congregation. The team looks to add new members every January, and is always glad for extra help around the luncheon in May.",
    graphicImage: "",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Linda Keithley",
    contactEmail: "linda.keithley@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Occasional meetings, annual luncheon in May",
    location: "",
    skillsNeeded: ["Event planning", "Fundraising", "Administration"],
    timeCommitment: "Seasonal"
  },
  {
    name: "Seasonal Ministry Teams",
    contactHeading: "Contact Pastor:",
    leader: "Emily Newby",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "Every year, 3 teams of 5-8 people form and work with our pastoral staff to plan and lead 4 months of ministry and programs in the life of FCC. It's an intensive but short-term and deeply meaningful commitment!",
    graphicImage: "",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Emily Newby",
    contactEmail: "emily.newby@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "4-month commitments",
    location: "",
    skillsNeeded: ["Leadership", "Planning", "Ministry"],
    timeCommitment: "4 months"
  },
  {
    name: "Welcome Team",
    contactHeading: "Contact Group Leader:",
    leader: "Rhonda Herdman",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Meetings occasionally. Volunteers needed for Sundays and special events.",
    regularMeetingTime: "",
    description: "Help visitors feel at home at FCC on Sundays by holding doors, handing out worship bulletins and welcome bags, answering questions, and generally sharing warmth and love with newcomers.",
    graphicImage: "",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Rhonda Herdman",
    contactEmail: "rhonda.herdman@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sundays and special events",
    location: "Church",
    skillsNeeded: ["Hospitality", "Communication", "Welcoming"],
    timeCommitment: "Sundays"
  },
  {
    name: "Youth Ministry Support Teams",
    contactHeading: "Contact Pastor:",
    leader: "Austin Staggs",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Service Opportunities during Sunday School, Wednesdays & Special Events",
    regularMeetingTime: "",
    description: "There are many ways to serve: as a Sunday school leader, camp driver, special event host, Wed evening meal preparer. Note that background checks are required.",
    graphicImage: "",
    recurringType: "Never",
    category: "Service & Ministry",
    contactPerson: "Austin Staggs",
    contactEmail: "austin.staggs@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sunday School, Wednesdays, Special Events",
    location: "Church",
    skillsNeeded: ["Teaching", "Driving", "Cooking", "Event hosting"],
    timeCommitment: "Varies"
  },
  {
    name: "42 Dominoes",
    contactHeading: "Contact Group Leader:",
    leader: "Dan Kerr",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Meets Weekly on Wednesdays at 9:30AM in the Gathering Area",
    regularMeetingTime: "Wednesdays at 9:30AM",
    description: "Whether you've played this classic Texas domino game for decades or want to pick up a new game, come play 42!",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:54e07266-c018-5287-98d8-0a51b7ec928c?invite=true&accept=true&promoid=YXPZFV9S&mv=other",
    recurringType: "Often",
    category: "Fellowship & Interest",
    contactPerson: "Dan Kerr",
    contactEmail: "dan.kerr@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Wednesdays at 9:30AM",
    location: "Gathering Area",
    skillsNeeded: [],
    timeCommitment: "Weekly"
  },
  {
    name: "Anjelita Best Food Pantry",
    contactHeading: "Contact Outreach Chair:",
    leader: "Jerry Tidwell",
    leaderContact: "",
    type: ["Partner Organization"],
    regularMeetingType: "Food Distribution Thursday Afternoons",
    regularMeetingTime: "Thursday Afternoons",
    description: "The Anjelita Best Food Pantry offers food to our Hood County neighbors in Oak Trail Shores on Thursdays from 1pm to 4pm.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:7ab6a385-d6c5-5b11-9aa7-34783472151b?invite=true&accept=true&promoid=YXPZFV9S&mv=other",
    recurringType: "Often",
    category: "Partner Organization",
    contactPerson: "Jerry Tidwell",
    contactEmail: "jerry.tidwell@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Thursdays 1pm-4pm",
    location: "Oak Trail Shores",
    skillsNeeded: [],
    timeCommitment: "Weekly"
  },
  {
    name: "Art Ministry",
    contactHeading: "Contact Pastor:",
    leader: "Pamala Vannoy",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "September: Mondays & Wednesdays 1pm-4pm; Art Studio Available 10-4 Weekdays",
    regularMeetingTime: "Mondays & Wednesdays 1pm-4pm",
    description: "The Art Ministry of First Christian Church is an opportunity to worship through various art media. We mostly use the Art Studio located across the hall from the Parlor. We do a variety of outreach based projects as well as opportunities to try out a variety of art styles, or bring your own project anytime.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA7:a76754bc-b5bb-581d-9a32-107d2c3242c2?invite=true&accept=true&promoid=YXPZFV9S&mv=other",
    recurringType: "Often",
    category: "Fellowship & Interest",
    contactPerson: "Pamala Vannoy",
    contactEmail: "pamala.vannoy@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Mondays & Wednesdays 1pm-4pm",
    location: "Art Studio",
    skillsNeeded: ["Art", "Creativity"],
    timeCommitment: "Weekly"
  },
  {
    name: "Centering Prayer Group",
    contactHeading: "Contact Group Leader:",
    leader: "Mary Waldson",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Meets Mondays at 6 P.M. in the Parlor",
    regularMeetingTime: "Mondays at 6 P.M.",
    description: "Come explore a variety of ancient contemplative practices!",
    graphicImage: "https://express.adobe.com/id/urn:aaid:sc:VA6C2:7ddfdc33-4007-4967-839a-c9924bbbcbfd?invite=true&accept=true&promoid=Z2G1FQKR&mv=other",
    recurringType: "Often",
    category: "Fellowship & Interest",
    contactPerson: "Mary Waldson",
    contactEmail: "mary.waldson@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Mondays at 6 P.M.",
    location: "Parlor",
    skillsNeeded: [],
    timeCommitment: "Weekly"
  },
  {
    name: "Contemplative Prayer",
    contactHeading: "Contact Pastor:",
    leader: "Candy Stroup",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Meets Weekly on Tuesdays at 2PM in the Parlor",
    regularMeetingTime: "Tuesdays at 2PM",
    description: "A leader shares readings and the group sits in 3 sessions of 15 minutes of silence.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:7ddfdc33-4007-4967-839a-c9924bbbcbfd?invite=true&accept=true&promoid=Z662FLTQ&mv=other",
    recurringType: "Often",
    category: "Fellowship & Interest",
    contactPerson: "Candy Stroup",
    contactEmail: "candy.stroup@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Tuesdays at 2PM",
    location: "Parlor",
    skillsNeeded: [],
    timeCommitment: "Weekly"
  },
  {
    name: "Disciples Class",
    contactHeading: "Contact Pastor:",
    leader: "Justin Jeter",
    leaderContact: "",
    type: ["Discipleship & Education"],
    regularMeetingType: "Meets Weekly (Sunday School)",
    regularMeetingTime: "Sunday School",
    description: "In the Disciples Class, scripture is shared in an interactive way that brings the text alive. Weekly classes combine teaching and discussion to provide a scriptural interpretation of culture and a cultural interpretation of scripture. Participants are invited to take a deep dive into familiar Bible stories and into lesser-known passages, to put them in historical context, and to apply them to modern life. The class is currently studyin the book of Job.",
    graphicImage: "",
    recurringType: "Often",
    category: "Discipleship & Education",
    contactPerson: "Justin Jeter",
    contactEmail: "justin.jeter@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sunday School",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Weekly"
  },
  {
    name: "Disciples Men's Prayer Group & Breakfast",
    contactHeading: "Contact Group Leader:",
    leader: "Dan Kerr",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Meets Weekly on Wednesdays at 7:30AM in the Gathering Area",
    regularMeetingTime: "Wednesdays at 7:30AM",
    description: "This long-running group meets every Wednesday (like clockwork!) for fellowship, prayer, and a devotional time. Participants take turns preparing and offering the weekly devotional. The group begins to gather as early as 6 AM, but the prayer and devotional time occurs at 7:30 AM, and many participants go out to breakfast afterward.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:6a623541-294e-522b-aeee-c2b12f47e07c?invite=true&accept=true&promoid=Z662FLTQ&mv=other",
    recurringType: "Often",
    category: "Fellowship & Interest",
    contactPerson: "Dan Kerr",
    contactEmail: "dan.kerr@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Wednesdays at 7:30AM",
    location: "Gathering Area",
    skillsNeeded: [],
    timeCommitment: "Weekly"
  },
  {
    name: "Disciples Women's Card Writing Ministry",
    contactHeading: "Contact Group Leader:",
    leader: "Janie Lewis",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Meets Monthly on Second Thursday in Room 7",
    regularMeetingTime: "Second Thursday monthly",
    description: "This group meets monthly for prayer, conversation, and to write cards to homebound persons and members of our prayer list.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:865396f6-777a-4362-b398-9a35c47aeb7d?invite=true&accept=true&promoid=Z662FLTQ&mv=other",
    recurringType: "Often",
    category: "Fellowship & Interest",
    contactPerson: "Janie Lewis",
    contactEmail: "janie.lewis@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Second Thursday monthly",
    location: "Room 7",
    skillsNeeded: ["Writing", "Prayer"],
    timeCommitment: "Monthly"
  },
  {
    name: "Pack the Pantry Volunteers",
    contactHeading: "Contact Pastor:",
    leader: "Austin Staggs",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Food Collected Last Sunday of the Month; Food Transported the follwing Thursday.",
    regularMeetingTime: "Last Sunday of month",
    description: "The last Sunday every month we collect food for the Angelita Best Food Pantry at the Ruth's Place Outreach Center in Oak Trail Shores. Check out the Gathering area for the most recent shopping list! Talk to Austin if you're interested in volunteering to take the food from FCC to the Pantry or distribute food on Thursday afternoons.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:7ab6a385-d6c5-5b11-9aa7-34783472151b?invite=true&accept=true&promoid=YXPZFV9S&mv=other",
    recurringType: "Often",
    category: "Service & Ministry",
    contactPerson: "Austin Staggs",
    contactEmail: "austin.staggs@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Last Sunday of month",
    location: "Church to Oak Trail Shores",
    skillsNeeded: ["Driving", "Organization"],
    timeCommitment: "Monthly"
  },
  {
    name: "Parkinson's Boxing Ministry",
    contactHeading: "Contact Group Leader:",
    leader: "Dorothy Weber",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Meets Weekly on Tuesdays and Fridays at 12:30. Does not meet the last Tuesday of each month.",
    regularMeetingTime: "Tuesdays and Fridays at 12:30",
    description: "Studies have shown that the fast-twitch movements of boxing help stave off the effects of Parkinson's disease, and this group exists to help. If you or a loved one have Parkinson's, you're welcome to participate, and the group is always looking for volunteers to help out.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:460ca4dd-0684-52f9-8a17-ce691e8079cd?invite=true&accept=true&promoid=Z662FLTQ&mv=other",
    recurringType: "Often",
    category: "Fellowship & Interest",
    contactPerson: "Dorothy Weber",
    contactEmail: "dorothy.weber@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Tuesdays and Fridays at 12:30",
    location: "",
    skillsNeeded: ["Physical activity", "Patience"],
    timeCommitment: "Weekly"
  },
  {
    name: "Pickleball",
    contactHeading: "Contact Group Leader:",
    leader: "Rob Snider",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Schedule Varies; See Sunday Bulletin for Pickleball Times",
    regularMeetingTime: "Varies",
    description: "Come play (or learn!) this fun game, make some new friends, and get some good exercise while you're at it. It's kind of like a cross between tennis and ping-pong, and it's great fun for all ages.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:b59ef912-b9fc-4fae-9069-e9c1b34b857f?invite=true&accept=true&promoid=Z662FLTQ&mv=other",
    recurringType: "Often",
    category: "Fellowship & Interest",
    contactPerson: "Rob Snider",
    contactEmail: "rob.snider@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Varies - see bulletin",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Flexible"
  },
  {
    name: "Respite Care Ministry",
    contactHeading: "Contact Group Leader:",
    leader: "Cheryl Frederick",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Meets Weekly on Fridays from 10am-4pm",
    regularMeetingTime: "Fridays from 10am-4pm",
    description: "This group exists to offer a safe place for seniors needing full-time care to share fellowship, food, and fun, so that caregivers get a break to run errands, take a nap, etc. Volunteers share fellowship and fun with guests, and the blessing is three-fold: for our guests, their caregivers AND our volunteers!",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:faa0a0c9-774d-4de0-b043-771fb3595f08?invite=true&accept=true&promoid=YXPZFV9S&mv=other",
    recurringType: "Often",
    category: "Service & Ministry",
    contactPerson: "Cheryl Frederick",
    contactEmail: "cheryl.frederick@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Fridays from 10am-4pm",
    location: "",
    skillsNeeded: ["Patience", "Compassion", "Caregiving"],
    timeCommitment: "Weekly"
  },
  {
    name: "Seekers Class",
    contactHeading: "Contract Class Leader:",
    leader: "Bradley Leake",
    leaderContact: "",
    type: ["Discipleship & Education"],
    regularMeetingType: "Meets for Sunday School",
    regularMeetingTime: "Sunday School",
    description: "Life is about discovering the right questions more than having the right answers. It's counterintuitive, isn't it? In a world that seeks certainty and winning over doubting and losing, it seems strange to intentionally seek out that which might be considered weak or vulnerable...but isn't that the way of Christ? What is the cross, if not the ultimate embodiment of loss and undefended love? Aren't questions the path to new wisdom? All of these are great questions!",
    graphicImage: "",
    recurringType: "Often",
    category: "Discipleship & Education",
    contactPerson: "Bradley Leake",
    contactEmail: "bradley.leake@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sunday School",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Weekly"
  },
  {
    name: "Tai Chi",
    contactHeading: "Contact Group Leader:",
    leader: "Bonnie Holmes",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Classes Mondays and Fridays at 10AM in the gym.",
    regularMeetingTime: "Mondays and Fridays at 10AM",
    description: "This group meets for mind- and body-centering movement.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:4fc12b70-5813-528c-a4d4-167c1f599d39?invite=true&accept=true&promoid=Z2G1FQKR&mv=other",
    recurringType: "Often",
    category: "Fellowship & Interest",
    contactPerson: "Bonnie Holmes",
    contactEmail: "bonnie.holmes@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Mondays and Fridays at 10AM",
    location: "Gym",
    skillsNeeded: [],
    timeCommitment: "Weekly"
  },
  {
    name: "Chancel Choir",
    contactHeading: "Contact Music Minister:",
    leader: "Josh Newby",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Rehearses Weekly on Wednesday evenings at 6:30PM",
    regularMeetingTime: "Wednesday evenings at 6:30PM",
    description: "Our choir gathers weekly to prepare to lead us in worship on Sunday morning. You don't have to be a top-flight singer; just someone who loves singing and loves God!",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:0e975f68-e306-510d-b7e0-e9a37544f523?invite=true&accept=true&promoid=Z662FLTQ&mv=other?preload=sharesheet",
    recurringType: "Yes",
    category: "Service & Ministry",
    contactPerson: "Josh Newby",
    contactEmail: "josh.newby@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Wednesday evenings at 6:30PM",
    location: "",
    skillsNeeded: ["Singing", "Music"],
    timeCommitment: "Weekly"
  },
  {
    name: "Chi-Rho & CYF",
    contactHeading: "Contact Pastor:",
    leader: "Austin Staggs",
    leaderContact: "",
    type: ["Discipleship & Education"],
    regularMeetingType: "Meets Weekly (Sunday School, Wednesday Evenings & Special Events)",
    regularMeetingTime: "Sunday School, Wednesday Evenings",
    description: "Students in grades 6-12 share food, fellowship, learning, worship, and fun.",
    graphicImage: "",
    recurringType: "Yes",
    category: "Discipleship & Education",
    contactPerson: "Austin Staggs",
    contactEmail: "austin.staggs@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sunday School, Wednesday Evenings & Special Events",
    location: "",
    skillsNeeded: [],
    timeCommitment: "Weekly"
  },
  {
    name: "Children's Ministry Teams",
    contactHeading: "Contact Pastor:",
    leader: "Emily Newby",
    leaderContact: "",
    type: ["Discipleship & Education"],
    regularMeetingType: "Meets Weekly (Sunday School) & Special Events",
    regularMeetingTime: "Sunday School & Special Events",
    description: "There are many ways to serve: as a Children's Worship leader, Pathfinder's Kids Club volunteer, camp driver, special event host, nursery helper, etc. Note that background checks are required.",
    graphicImage: "",
    recurringType: "Yes",
    category: "Discipleship & Education",
    contactPerson: "Emily Newby",
    contactEmail: "emily.newby@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sunday School & Special Events",
    location: "",
    skillsNeeded: ["Teaching", "Childcare", "Driving"],
    timeCommitment: "Weekly"
  },
  {
    name: "Handbell Choir",
    contactHeading: "Contact Group Leader:",
    leader: "Emily Graham",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Rehearses Wednesdays at 5:30",
    regularMeetingTime: "Wednesdays at 5:30",
    description: "Our handbell choir is a great way to get involved with our music ministries! Come ring with a group and together make some beautiful music.",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:e202c8d3-caab-4cc9-a684-146d1935493a?invite=true&accept=true&promoid=Z2G1FQKR&mv=other?preload=sharesheet",
    recurringType: "Yes",
    category: "Fellowship & Interest",
    contactPerson: "Emily Graham",
    contactEmail: "emily.graham@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Wednesdays at 5:30",
    location: "",
    skillsNeeded: ["Music", "Handbells"],
    timeCommitment: "Weekly"
  },
  {
    name: "Kitchen Crew",
    contactHeading: "Contact Group Leader:",
    leader: "Linda Keithley",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Serves Weekly on Sundays",
    regularMeetingTime: "Sundays",
    description: "This amazing team manages the kitchen, provides refreshments and hospitality on Sunday mornings, and occasionally facilitates food service for other special events. And they have a lot of fun while doing it!",
    graphicImage: "https://new.express.adobe.com/id/urn:aaid:sc:VA6C2:556001cb-c7ab-5263-a73f-bd754777b95c?invite=true&accept=true&promoid=Z662FLTQ&mv=other?preload=sharesheet",
    recurringType: "Yes",
    category: "Service & Ministry",
    contactPerson: "Linda Keithley",
    contactEmail: "linda.keithley@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sundays",
    location: "Kitchen",
    skillsNeeded: ["Cooking", "Hospitality"],
    timeCommitment: "Weekly"
  },
  {
    name: "Ladies Who Lunch",
    contactHeading: "Contact Group Leader:",
    leader: "Tommie Hicks",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Meets Monthly",
    regularMeetingTime: "Monthly",
    description: "This group meets monthly at Randy's Grill for lunch and fellowship, and all are welcome!",
    graphicImage: "",
    recurringType: "Yes",
    category: "Fellowship & Interest",
    contactPerson: "Tommie Hicks",
    contactEmail: "tommie.hicks@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Monthly",
    location: "Randy's Grill",
    skillsNeeded: [],
    timeCommitment: "Monthly"
  },
  {
    name: "Library",
    contactHeading: "Contact Church Librarian:",
    leader: "Ann Lockard",
    leaderContact: "",
    type: ["Discipleship & Education"],
    regularMeetingType: "Librarian available Sunday Mornings",
    regularMeetingTime: "Sunday Mornings",
    description: "The FCC Library is a wonderful resource for books and other media for all ages. Check out our collection of fiction and non-fiction at our circulation desk. If you have any questions, speak with our church librarian, Ann Lockard!",
    graphicImage: "",
    recurringType: "Yes",
    category: "Discipleship & Education",
    contactPerson: "Ann Lockard",
    contactEmail: "ann.lockard@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sunday Mornings",
    location: "Library",
    skillsNeeded: ["Organization", "Library skills"],
    timeCommitment: "Weekly"
  },
  {
    name: "Praise Team",
    contactHeading: "Contact Music Minister:",
    leader: "Josh Newby",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Rehearses Thursdays at 5:30",
    regularMeetingTime: "Thursdays at 5:30",
    description: "Our Praise Team leads worship during our 9AM services and at special events throughout the year. Talk to Josh Newby if you have a musical gift you're interested in sharing!",
    graphicImage: "",
    recurringType: "Yes",
    category: "Service & Ministry",
    contactPerson: "Josh Newby",
    contactEmail: "josh.newby@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Thursdays at 5:30",
    location: "",
    skillsNeeded: ["Music", "Singing", "Instruments"],
    timeCommitment: "Weekly"
  },
  {
    name: "Visiting Ministry",
    contactHeading: "Contact Pastor:",
    leader: "Candy Stroup",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Ongoing with Meetings Quarterly",
    regularMeetingTime: "Quarterly meetings",
    description: "This ministry of First Christian Church is a great way to get involved if you want to show the love of church to those who are unable to attend church in person, but want more fellowship with the congregation. Teams of two will visit some of the same folks regularly so that Christian relationships can be formed and supported.",
    graphicImage: "",
    recurringType: "Yes",
    category: "Service & Ministry",
    contactPerson: "Candy Stroup",
    contactEmail: "candy.stroup@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Ongoing with quarterly meetings",
    location: "Various",
    skillsNeeded: ["Visiting", "Compassion", "Communication"],
    timeCommitment: "Ongoing"
  },
  {
    name: "Wayfinding Team",
    contactHeading: "Contact Pastor:",
    leader: "Justin Jeter",
    leaderContact: "",
    type: ["Service & Ministry"],
    regularMeetingType: "Individuals serve weekly on Sunday mornings. Team meets monthly (first Sunday at 12:15PM in the Parlor)",
    regularMeetingTime: "Sunday mornings",
    description: "Help newcomers find their place and their ministry here at FCC.",
    graphicImage: "",
    recurringType: "Yes",
    category: "Service & Ministry",
    contactPerson: "Justin Jeter",
    contactEmail: "justin.jeter@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Sunday mornings",
    location: "Church",
    skillsNeeded: ["Hospitality", "Communication"],
    timeCommitment: "Weekly"
  },
  {
    name: "Women's Book Club",
    contactHeading: "Contact Group Leader:",
    leader: "Donna Coates",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "Meets Monthly on third Thursdays at 10AM in the library. Does not meet November or December.",
    regularMeetingTime: "Third Thursdays at 10AM",
    description: "This group meets for friendship, casual conversation and discussion of a monthly book.",
    graphicImage: "",
    recurringType: "Yes",
    category: "Fellowship & Interest",
    contactPerson: "Donna Coates",
    contactEmail: "donna.coates@fccgranbury.org",
    contactPhone: "",
    meetingSchedule: "Third Thursdays at 10AM",
    location: "Library",
    skillsNeeded: ["Reading", "Discussion"],
    timeCommitment: "Monthly"
  },
  {
    name: "Young Adult Outings",
    contactHeading: "",
    leader: "",
    leaderContact: "",
    type: ["Fellowship & Interest"],
    regularMeetingType: "",
    regularMeetingTime: "",
    description: "This group meets seasonally to go out on the town.",
    graphicImage: "https://express.adobe.com/id/urn:aaid:sc:VA6C2:bd0208c5-aba7-5985-b277-2eef597a3079?invite=true&accept=true&promoid=Z2G1FQKR&mv=other",
    recurringType: "Yes",
    category: "Fellowship & Interest",
    contactPerson: "",
    contactEmail: "",
    contactPhone: "",
    meetingSchedule: "Seasonal",
    location: "Various",
    skillsNeeded: [],
    timeCommitment: "Seasonal"
  }
];

// Categories to create
const categories = [
  { name: "Service & Ministry", description: "Groups focused on serving others and ministry work", color: "#3B82F6" },
  { name: "Fellowship & Interest", description: "Groups for fellowship and shared interests", color: "#10B981" },
  { name: "Discipleship & Education", description: "Groups focused on learning and spiritual growth", color: "#8B5CF6" },
  { name: "Partner Organization", description: "External organizations we partner with", color: "#F59E0B" }
];

async function loadMinistryData() {
  try {
    console.log('Loading ministry data...');

    // First, create categories
    console.log('Creating categories...');
    for (const category of categories) {
      await db.insert(ministryCategories).values(category).onConflictDoNothing();
    }

    // Then, create ministry teams
    console.log('Creating ministry teams...');
    for (const ministry of ministryData) {
      await db.insert(ministryTeams).values(ministry).onConflictDoNothing();
    }

    console.log('Ministry data loaded successfully!');
  } catch (error) {
    console.error('Error loading ministry data:', error);
    throw error;
  }
}

// Run the script
loadMinistryData()
  .then(() => {
    console.log('Script completed successfully');
    process.exit(0);
  })
  .catch((error) => {
    console.error('Script failed:', error);
    process.exit(1);
  });
